// Generated by valnivo-labs/foundation, @valnivo_labs/agreement 0.4.0. Do not edit.
// Change it there, then: npm run emit:code -- agreement valnivo <this file>
// The fingerprint at the end is sha-256 of everything between this header's
// blank line and the fingerprint line; this product's test recomputes it.

/**
 * A file several people sign, and a file somebody acknowledges receiving —
 * the two first kinds of Valnivo Sign (owner, 2026-09-30,
 * `ledgger/docs/valnivo-sign.md` §4).
 *
 * Both are **version-2** `@valnivo_labs/signing` documents: parties `p1` to
 * `pN`, `p1` proposing. **What is signed is the file's fingerprint, never the
 * file**: its SHA-256, name, media type, size and page count, with a title and
 * who signs it. So a contract of any length fits, the service that stores the
 * signatures never needs the file in the clear, and anybody holding the file
 * can check it is the one signed.
 *
 * - `labs.acknowledgement` — `p1` sends a file and `p2` confirms they received
 *   it. Exactly two parties. Nobody closes it.
 * - `labs.agreement` — two to ten parties sign, in any order or in sequence.
 *   Once signed, only `p1` closes it: *replaced* by a corrected version
 *   everybody signed again (it is never edited), or *ended*.
 *
 * **What this does not decide.** An e-mail address is recorded, not proved;
 * proving it is the product's (a verified sign-in). A party signing *for* an
 * organisation is recorded as that party's own statement, and nothing here
 * checks their authority to make it. Neither makes anything legally binding:
 * the product says what the law does and does not give it.
 *
 * Only the pure part is here: no storage, no network, no account.
 */
import {
  PARTIES_VERSION,
  newNonce,
  partiesDocumentProblems,
  partyId,
  verifyPartiesProof,
  type HistoryEntry,
  type PartiesDocument,
  type PartiesKind,
  type PartiesProof,
  type PartiesState,
  type PartiesVerdict,
  type PartyId,
  type SigningOrder,
} from './signing.generated'

export const ACKNOWLEDGEMENT: PartiesKind = { kind: 'labs.acknowledgement', proposerMayClose: false, outcomes: [] }
export const AGREEMENT: PartiesKind = { kind: 'labs.agreement', proposerMayClose: true, outcomes: ['replaced', 'ended'] }

export type AgreementOutcome = 'replaced' | 'ended'

/**
 * Any kind of file may be signed (owner, 2026-10-03): what the parties sign is its fingerprint,
 * and the file itself is never changed. A PDF is the one type with pages, which signatures can
 * be placed on and drawn into; every other file carries `pages: 0`.
 */
export const PDF = 'application/pdf'
/** A media type as `type/subtype`, lower case, no parameters: `image/png`, `application/octet-stream`. */
export type MediaType = string
export const MEDIA_TYPE = /^[a-z0-9][a-z0-9!#$&^_.+-]{0,63}\/[a-z0-9][a-z0-9!#$&^_.+-]{0,63}$/

/** Whether a signed file is a PDF, with pages a signature can be placed on. */
export const isPdf = (file: { mediaType: string }): boolean => file.mediaType === PDF

export const TITLE_MAX = 120
export const FILE_NAME_MAX = 200
export const LABEL_MAX = 60
export const ORGANISATION_MAX = 120
export const EMAIL_MAX = 254
/** Fifty megabytes: past this it is not a document somebody reads before signing. */
export const FILE_BYTES_MAX = 50 * 1024 * 1024
export const PAGES_MAX = 2000

export interface SignedFile {
  /** Lowercase hex SHA-256 of the file's bytes. */
  sha256: string
  name: string
  mediaType: MediaType
  bytes: number
  /** A PDF's page count; 0 for any other file. */
  pages: number
}

export interface Signer {
  /** Which party this is, `p1` to `pN`, in the same order as the document's parties. */
  party: PartyId
  /** The address the party is invited at, lower case. The product proves it; this records it. */
  email: string
  /** What they sign as — "Tenant", "Buyer" — or empty. */
  label: string
  /** The organisation they say they sign for, or empty. Their statement, not a verified fact. */
  organisation: string
}

export interface Replaces {
  documentId: string
  termsPrint: string
}

export interface AgreementContent {
  title: string
  file: SignedFile
  signers: Signer[]
  /** YYYY-MM-DD, the last day it may be signed, or null for no deadline. */
  signBy: string | null
  /** Present on a correction: the agreement it replaces, which `p1` closes as *replaced* once this is signed. */
  replaces?: Replaces
}

export type AcknowledgementContent = Omit<AgreementContent, 'replaces'>

export type AgreementDocument = PartiesDocument<AgreementContent>

const CONTENT_KEYS = ['title', 'file', 'signers', 'signBy', 'replaces']
const FILE_KEYS = ['sha256', 'name', 'mediaType', 'bytes', 'pages']
const SIGNER_KEYS = ['party', 'email', 'label', 'organisation']
const HEX64 = /^[0-9a-f]{64}$/

export function isDate(value: unknown): value is string {
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false
  const d = new Date(`${value}T00:00:00Z`)
  return !Number.isNaN(d.getTime()) && d.toISOString().slice(0, 10) === value
}

const plausibleEmail = (v: unknown): v is string =>
  typeof v === 'string' && v.length <= EMAIL_MAX && v === v.trim().toLowerCase() && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)

const text = (v: unknown, max: number, required: boolean): boolean =>
  typeof v === 'string' && v.length <= max && (!required || v.trim().length > 0) && v === v.trim()

/**
 * Every reason this is not an agreement or an acknowledgement, as short codes;
 * empty means it is one. The content is a closed set of fields: anything else —
 * a clause, an amount, a place to put the file itself — has nowhere to go.
 */
export function agreementProblems(doc: unknown): string[] {
  const out = partiesDocumentProblems(doc)
  if (out.includes('not-document')) return out
  const d = doc as PartiesDocument<Record<string, unknown>>
  const ack = d.kind === ACKNOWLEDGEMENT.kind
  if (!ack && d.kind !== AGREEMENT.kind) out.push('other-kind')
  const c = d.content
  if (!c || typeof c !== 'object' || Array.isArray(c)) return [...out, 'content']
  for (const key of Object.keys(c)) if (!CONTENT_KEYS.includes(key)) out.push(`unknown-content:${key}`)
  if (!text(c.title, TITLE_MAX, true)) out.push('title')
  if (!('signBy' in c) || (c.signBy !== null && !isDate(c.signBy))) out.push('sign-by')

  const f = c.file as Record<string, unknown> | undefined
  if (!f || typeof f !== 'object' || Array.isArray(f)) out.push('file')
  else {
    for (const key of Object.keys(f)) if (!FILE_KEYS.includes(key)) out.push(`unknown-file:${key}`)
    if (typeof f.sha256 !== 'string' || !HEX64.test(f.sha256)) out.push('file-sha256')
    if (!text(f.name, FILE_NAME_MAX, true)) out.push('file-name')
    const media = typeof f.mediaType === 'string' && MEDIA_TYPE.test(f.mediaType)
    if (!media) out.push('file-media-type')
    if (!Number.isInteger(f.bytes) || (f.bytes as number) < 1 || (f.bytes as number) > FILE_BYTES_MAX) out.push('file-bytes')
    const pages = f.pages as number
    if (!Number.isInteger(pages) || (f.mediaType === PDF ? pages < 1 || pages > PAGES_MAX : pages !== 0)) out.push('file-pages')
  }

  const parties = Array.isArray(d.parties) ? d.parties : []
  const signers = c.signers
  if (!Array.isArray(signers) || signers.length !== parties.length) out.push('signers')
  else {
    const emails = new Set<string>()
    signers.forEach((s: unknown, i: number) => {
      const signer = s as Record<string, unknown>
      if (!signer || typeof signer !== 'object' || Object.keys(signer).some((k) => !SIGNER_KEYS.includes(k)) || SIGNER_KEYS.some((k) => !(k in signer))) {
        out.push(`signer:${i}`)
        return
      }
      if (signer.party !== partyId(i)) out.push(`signer-party:${i}`)
      if (!plausibleEmail(signer.email)) out.push(`signer-email:${i}`)
      else if (emails.has(signer.email)) out.push(`signer-email-twice:${i}`)
      else emails.add(signer.email)
      if (!text(signer.label, LABEL_MAX, false)) out.push(`signer-label:${i}`)
      if (!text(signer.organisation, ORGANISATION_MAX, false)) out.push(`signer-organisation:${i}`)
    })
  }

  if (ack) {
    if (parties.length !== 2) out.push('acknowledgement-parties')
    if ('replaces' in c) out.push('acknowledgement-replaces')
  } else if ('replaces' in c) {
    const r = c.replaces as Record<string, unknown> | undefined
    if (!r || typeof r !== 'object' || Object.keys(r).some((k) => k !== 'documentId' && k !== 'termsPrint') || typeof r.documentId !== 'string' || !r.documentId || typeof r.termsPrint !== 'string' || !HEX64.test(r.termsPrint)) {
      out.push('replaces')
    }
  }
  return out
}

/** A new agreement ready to propose: `names[0]` is the proposer's, in the same order as `content.signers`. */
export function agreementDocument(content: AgreementContent, names: readonly string[], order: SigningOrder): AgreementDocument {
  return {
    version: PARTIES_VERSION,
    kind: AGREEMENT.kind,
    parties: names.map((name, i) => ({ id: partyId(i), name })),
    order,
    content,
    nonce: newNonce(),
  }
}

/** A new acknowledgement: `p1` sends, `p2` confirms. */
export function acknowledgementDocument(content: AcknowledgementContent, names: readonly [string, string]): PartiesDocument<AcknowledgementContent> {
  return {
    version: PARTIES_VERSION,
    kind: ACKNOWLEDGEMENT.kind,
    parties: names.map((name, i) => ({ id: partyId(i), name })),
    order: 'any',
    content,
    nonce: newNonce(),
  }
}

/**
 * Past its sign-by day with a signature still missing. The product stops
 * taking signatures then; it is not a status the history records, because
 * nobody acted.
 */
export function isExpired(content: Pick<AgreementContent, 'signBy'>, state: PartiesState, today: string): boolean {
  return state.status === 'proposed' && content.signBy !== null && today > content.signBy
}

/** How a closed agreement was closed, read off its last `closed` entry. */
export function closedAs(entries: readonly HistoryEntry<PartyId>[]): AgreementOutcome | null {
  const closing = [...entries].sort((a, b) => b.seq - a.seq).find((e) => e.act === 'closed')
  return closing && (AGREEMENT.outcomes as readonly string[]).includes(closing.detail) ? (closing.detail as AgreementOutcome) : null
}

/** A proof of either kind checked on its own: the shared layer, then this package's rules for the content and the closing. */
export async function verifyAgreementProof(proof: PartiesProof): Promise<PartiesVerdict & { closedAs: AgreementOutcome | null }> {
  const kind = proof.document?.kind === ACKNOWLEDGEMENT.kind ? ACKNOWLEDGEMENT : AGREEMENT
  const verdict = await verifyPartiesProof(proof, kind)
  const problems = [...verdict.problems]
  for (const p of agreementProblems(proof.document)) if (!problems.includes(p)) problems.push(p)
  const outcome = closedAs(proof.entries)
  if (verdict.state?.status === 'closed' && !outcome) problems.push('closing-outcome')
  return { ...verdict, authentic: problems.length === 0, problems, closedAs: outcome }
}

// --- What a party's entry records when they put their name to it ---------------

/**
 * Where a party puts their name to the document — proposing, opening, signing —
 * their entry's `detail` is **their verified address**, optionally followed by
 * the fingerprint of **the image of their signature** they chose to show, and
 * **where on the document** they placed it:
 *
 *     tom@example.eu
 *     tom@example.eu sha256:<64 hex>
 *     tom@example.eu sha256:<64 hex> place:<page>:<x>:<y>:<width>
 *
 * `page` counts from 1; `x`, `y` (the image's bottom-left corner, from the page's
 * bottom-left) and `width` are fractions of the page, three decimals. Binding
 * both into the signed entry means neither the picture nor where it sits can be
 * changed afterwards without the entry failing to check. It is a picture shown
 * beside the real signature, which is the key's — never a signature in itself.
 */
export const MARK_PREFIX = 'sha256:'
export const PLACE_PREFIX = 'place:'

export interface Placement {
  page: number
  x: number
  y: number
  width: number
}

const fraction = (n: number) => Math.min(1, Math.max(0, Math.round(n * 1000) / 1000))
const PLACE = /^place:([1-9][0-9]{0,3}):(0|1|0\.[0-9]{1,3}|1\.0{1,3}):(0|1|0\.[0-9]{1,3}|1\.0{1,3}):(0\.[0-9]{1,3}|1|1\.0{1,3})$/

export function placementText(p: Placement): string {
  return `${PLACE_PREFIX}${Math.max(1, Math.floor(p.page))}:${fraction(p.x)}:${fraction(p.y)}:${fraction(p.width) || 0.001}`
}

export function readPlacement(text: string): Placement | null {
  const m = PLACE.exec(text)
  return m ? { page: Number(m[1]), x: Number(m[2]), y: Number(m[3]), width: Number(m[4]) } : null
}

export function signedDetail(email: string, markSha256?: string | null, placement?: Placement | null): string {
  const address = email.trim().toLowerCase()
  if (!markSha256) return address
  return placement ? `${address} ${MARK_PREFIX}${markSha256} ${placementText(placement)}` : `${address} ${MARK_PREFIX}${markSha256}`
}

/** The address, the image fingerprint and the placement an entry's detail records, or null when it is not one of these. */
export function readSignedDetail(detail: string): { email: string; markSha256: string | null; placement: Placement | null } | null {
  const [email, mark, place, ...rest] = detail.split(' ')
  if (rest.length || !email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || email !== email.toLowerCase()) return null
  if (mark === undefined) return { email, markSha256: null, placement: null }
  if (!mark.startsWith(MARK_PREFIX) || !/^[0-9a-f]{64}$/.test(mark.slice(MARK_PREFIX.length))) return null
  const markSha256 = mark.slice(MARK_PREFIX.length)
  if (place === undefined) return { email, markSha256, placement: null }
  const placement = readPlacement(place)
  return placement ? { email, markSha256, placement } : null
}
// foundation-fingerprint: 9f90db10bf448213eb5ed3b745ce8d50b50ae505206c88ae8c9174b82d790405
