// Generated by valnivo-labs/foundation, @valnivo_labs/family 0.1.0. Do not edit.
// Change it there, then: npm run emit:code -- family valnivo <this file>
// The fingerprint at the end is sha-256 of everything between this header's
// blank line and the fingerprint line; this product's test recomputes it.

/**
 * The Valnivo Labs products, as each of them names the others (owner, 2026-10-02).
 *
 * Every product carries a block linking to its siblings, drawn in its own style;
 * this is the one list behind all of them, so the products never disagree about
 * which exist, where they are, or what they are for. Words and addresses only —
 * the markup and the look stay in each product.
 *
 * **Only what serves something today is listed**: a product joins when its
 * address answers, never before, and an unannounced one is never written here,
 * not even as a placeholder, because whatever is here ends up in a page's HTML.
 * The links are plain links to the other sites, so search engines can follow
 * them; a product never links to itself (`siblingsOf`).
 */

export const FAMILY_LANGS = ['en', 'fr', 'de', 'es', 'it', 'pt', 'nl', 'pl', 'ar'] as const
export type FamilyLang = (typeof FAMILY_LANGS)[number]

export type FamilyId = 'valnivo' | 'sign' | 'moien'

export type FamilyProduct = {
  id: FamilyId
  /** As `@valnivo_labs/identity` names it, never translated. */
  name: string
  /** The product's public address: the page a link should land on. */
  url: string
  /** What it is for, in a few words, for the public. */
  line: Record<FamilyLang, string>
}

export const FAMILY: readonly FamilyProduct[] = [
  {
    id: 'valnivo',
    name: 'Valnivo',
    url: 'https://valnivo.eu/',
    line: {
      en: 'Plan your money and see where it could be in a few years.',
      fr: 'Planifiez votre argent et voyez où il pourrait en être dans quelques années.',
      de: 'Planen Sie Ihr Geld und sehen Sie, wo es in ein paar Jahren stehen könnte.',
      es: 'Planifique su dinero y vea dónde podría estar dentro de unos años.',
      it: 'Pianifichi il suo denaro e veda dove potrebbe arrivare tra qualche anno.',
      pt: 'Planeie o seu dinheiro e veja onde poderá estar daqui a alguns anos.',
      nl: 'Plan uw geld en zie waar het over een paar jaar zou kunnen staan.',
      pl: 'Zaplanuj swoje pieniądze i zobacz, gdzie mogą być za kilka lat.',
      ar: 'خطّط لأموالك واعرف أين قد تكون بعد بضع سنوات.',
    },
  },
  {
    id: 'sign',
    name: 'Valnivo Sign',
    url: 'https://valnivosign.eu/',
    line: {
      en: 'Sign documents and contracts online with other people.',
      fr: 'Signez des documents et des contrats en ligne avec d’autres personnes.',
      de: 'Unterschreiben Sie Dokumente und Verträge online mit anderen Personen.',
      es: 'Firme documentos y contratos en línea con otras personas.',
      it: 'Firmi documenti e contratti online con altre persone.',
      pt: 'Assine documentos e contratos online com outras pessoas.',
      nl: 'Onderteken documenten en contracten online met andere mensen.',
      pl: 'Podpisuj dokumenty i umowy online z innymi osobami.',
      ar: 'وقّع المستندات والعقود عبر الإنترنت مع أشخاص آخرين.',
    },
  },
  {
    id: 'moien',
    name: 'Moien',
    url: 'https://luxembourgish.app/',
    line: {
      en: 'A free Luxembourgish course, with real recordings of how words are said.',
      fr: 'Un cours de luxembourgeois gratuit, avec de vrais enregistrements de la prononciation.',
      de: 'Ein kostenloser Luxemburgischkurs mit echten Aufnahmen der Aussprache.',
      es: 'Un curso gratuito de luxemburgués, con grabaciones reales de cómo se pronuncian las palabras.',
      it: 'Un corso gratuito di lussemburghese, con vere registrazioni della pronuncia.',
      pt: 'Um curso gratuito de luxemburguês, com gravações reais da pronúncia das palavras.',
      nl: 'Een gratis cursus Luxemburgs, met echte opnames van hoe woorden worden uitgesproken.',
      pl: 'Bezpłatny kurs luksemburskiego z prawdziwymi nagraniami wymowy słów.',
      ar: 'دورة مجانية في اللغة اللوكسمبورغية، مع تسجيلات حقيقية لطريقة نطق الكلمات.',
    },
  },
]

/** The block's heading, beside the products it lists. */
export const FAMILY_HEADING: Record<FamilyLang, string> = {
  en: 'Also from Valnivo Labs',
  fr: 'Aussi de Valnivo Labs',
  de: 'Ebenfalls von Valnivo Labs',
  es: 'También de Valnivo Labs',
  it: 'Anche da Valnivo Labs',
  pt: 'Também da Valnivo Labs',
  nl: 'Ook van Valnivo Labs',
  pl: 'Również od Valnivo Labs',
  ar: 'أيضًا من Valnivo Labs',
}

const langOf = (lang: string): FamilyLang => ((FAMILY_LANGS as readonly string[]).includes(lang) ? (lang as FamilyLang) : 'en')

/** Every listed product but this one, in the list's order. */
export const siblingsOf = (id: FamilyId): FamilyProduct[] => FAMILY.filter((p) => p.id !== id)

/** A product's line in a language, English for one the list does not carry. */
export const lineOf = (product: FamilyProduct, lang: string): string => product.line[langOf(lang)]

/** The heading in a language, English for one the list does not carry. */
export const familyHeading = (lang: string): string => FAMILY_HEADING[langOf(lang)]
// foundation-fingerprint: 5f8b5b6169d82b77c947ddf806ecfea828d5b285860d5301dfcfde2597c90591
