// Generated by valnivo-labs/foundation, @valnivo_labs/identity 0.2.0. Do not edit.
// Change it there, then: npm run emit -- valnivo ts <this file>
// A test in this product should check IDENTITY_FINGERPRINT against the payload
// (sha-256 of JSON.stringify(IDENTITY_PAYLOAD)), so an edit here fails.

export const IDENTITY_PAYLOAD = {
  "version": "0.2.0",
  "organisation": {
    "name": "Valnivo Labs",
    "kind": "trade-name",
    "country": "LU",
    "url": "https://github.com/valnivo-labs"
  },
  "product": {
    "id": "valnivo",
    "name": "Valnivo",
    "url": "https://valnivo.eu"
  },
  "sentences": {
    "en": {
      "providedBy": "Valnivo is provided by Valnivo Labs.",
      "byline": "Provided by Valnivo Labs",
      "tradeName": "Valnivo Labs is a trade name, not a registered company.",
      "controller": "The data controller is Valnivo Labs, based in Luxembourg, which develops and runs Valnivo. Valnivo Labs is a trade name, not a registered company: if you need the controller named for a formal request or a complaint to a supervisory authority, ask at the address below and it will be given to you.",
      "offeredBy": "Valnivo is developed and offered by Valnivo Labs, based in Luxembourg. Valnivo Labs is a trade name, not a registered company."
    },
    "fr": {
      "providedBy": "Valnivo est proposé par Valnivo Labs.",
      "byline": "Proposé par Valnivo Labs",
      "tradeName": "Valnivo Labs est un nom commercial, et non une société immatriculée.",
      "controller": "Le responsable du traitement est Valnivo Labs, établi au Luxembourg, qui développe et exploite Valnivo. Valnivo Labs est un nom commercial, et non une société immatriculée : si vous avez besoin que le responsable soit nommé pour une demande formelle ou une réclamation auprès d’une autorité de contrôle, écrivez à l’adresse ci-dessous et son nom vous sera communiqué.",
      "offeredBy": "Valnivo est développé et proposé par Valnivo Labs, établi au Luxembourg. Valnivo Labs est un nom commercial, et non une société immatriculée."
    },
    "de": {
      "providedBy": "Valnivo wird von Valnivo Labs bereitgestellt.",
      "byline": "Bereitgestellt von Valnivo Labs",
      "tradeName": "Valnivo Labs ist ein Handelsname und keine eingetragene Gesellschaft.",
      "controller": "Verantwortlicher ist Valnivo Labs mit Sitz in Luxemburg, das Valnivo entwickelt und betreibt. Valnivo Labs ist ein Handelsname und keine eingetragene Gesellschaft: Wird der Verantwortliche für einen förmlichen Antrag oder eine Beschwerde bei einer Aufsichtsbehörde namentlich benötigt, wird der Name auf Anfrage an die unten stehende Adresse mitgeteilt.",
      "offeredBy": "Valnivo wird von Valnivo Labs mit Sitz in Luxemburg entwickelt und angeboten. Valnivo Labs ist ein Handelsname und keine eingetragene Gesellschaft."
    },
    "es": {
      "providedBy": "Valnivo lo ofrece Valnivo Labs.",
      "byline": "Ofrecido por Valnivo Labs",
      "tradeName": "Valnivo Labs es un nombre comercial, no una sociedad registrada.",
      "controller": "El responsable del tratamiento es Valnivo Labs, con sede en Luxemburgo, que desarrolla y gestiona Valnivo. Valnivo Labs es un nombre comercial, no una sociedad registrada: si necesita que se identifique al responsable para una solicitud formal o una reclamación ante una autoridad de control, pregunte en la dirección indicada abajo y se le facilitará su nombre.",
      "offeredBy": "Valnivo lo desarrolla y ofrece Valnivo Labs, con sede en Luxemburgo. Valnivo Labs es un nombre comercial, no una sociedad registrada."
    },
    "it": {
      "providedBy": "Valnivo è offerto da Valnivo Labs.",
      "byline": "Offerto da Valnivo Labs",
      "tradeName": "Valnivo Labs è un nome commerciale, non una società registrata.",
      "controller": "Il titolare del trattamento è Valnivo Labs, con sede in Lussemburgo, che sviluppa e gestisce Valnivo. Valnivo Labs è un nome commerciale, non una società registrata: se ha bisogno che il titolare sia indicato per nome per una richiesta formale o un reclamo a un’autorità di controllo, lo chieda all’indirizzo qui sotto e le sarà comunicato.",
      "offeredBy": "Valnivo è sviluppato e offerto da Valnivo Labs, con sede in Lussemburgo. Valnivo Labs è un nome commerciale, non una società registrata."
    },
    "pt": {
      "providedBy": "O Valnivo é disponibilizado pela Valnivo Labs.",
      "byline": "Disponibilizado pela Valnivo Labs",
      "tradeName": "A Valnivo Labs é um nome comercial, não uma sociedade registada.",
      "controller": "O responsável pelo tratamento é a Valnivo Labs, com sede no Luxemburgo, que desenvolve e gere o Valnivo. A Valnivo Labs é um nome comercial, não uma sociedade registada: se precisar que o responsável seja identificado para um pedido formal ou uma reclamação junto de uma autoridade de controlo, peça-o no endereço abaixo e o nome ser-lhe-á comunicado.",
      "offeredBy": "O Valnivo é desenvolvido e disponibilizado pela Valnivo Labs, com sede no Luxemburgo. A Valnivo Labs é um nome comercial, não uma sociedade registada."
    },
    "nl": {
      "providedBy": "Valnivo wordt aangeboden door Valnivo Labs.",
      "byline": "Aangeboden door Valnivo Labs",
      "tradeName": "Valnivo Labs is een handelsnaam, geen ingeschreven vennootschap.",
      "controller": "De verwerkingsverantwoordelijke is Valnivo Labs, gevestigd in Luxemburg, dat Valnivo ontwikkelt en beheert. Valnivo Labs is een handelsnaam, geen ingeschreven vennootschap: als u de verwerkingsverantwoordelijke bij naam nodig hebt voor een formeel verzoek of een klacht bij een toezichthoudende autoriteit, vraag er dan naar op het adres hieronder en de naam wordt u meegedeeld.",
      "offeredBy": "Valnivo wordt ontwikkeld en aangeboden door Valnivo Labs, gevestigd in Luxemburg. Valnivo Labs is een handelsnaam, geen ingeschreven vennootschap."
    },
    "pl": {
      "providedBy": "Valnivo jest udostępniane przez Valnivo Labs.",
      "byline": "Udostępniane przez Valnivo Labs",
      "tradeName": "Valnivo Labs to nazwa handlowa, a nie zarejestrowana spółka.",
      "controller": "Administratorem danych jest Valnivo Labs z siedzibą w Luksemburgu, które rozwija i prowadzi Valnivo. Valnivo Labs to nazwa handlowa, a nie zarejestrowana spółka: jeżeli do formalnego wniosku lub skargi do organu nadzorczego potrzebne jest imię i nazwisko administratora, zostaną one podane na prośbę wysłaną na adres poniżej.",
      "offeredBy": "Valnivo jest rozwijane i udostępniane przez Valnivo Labs z siedzibą w Luksemburgu. Valnivo Labs to nazwa handlowa, a nie zarejestrowana spółka."
    },
    "ar": {
      "providedBy": "يقدّم Valnivo Labs تطبيق Valnivo.",
      "byline": "مقدَّم من Valnivo Labs",
      "tradeName": "Valnivo Labs اسم تجاري، وليس شركة مسجّلة.",
      "controller": "المسؤول عن معالجة البيانات هو Valnivo Labs، ومقره لوكسمبورغ، وهو الذي يطوّر Valnivo ويديره. Valnivo Labs اسم تجاري، وليس شركة مسجّلة: إذا احتجت إلى اسم المسؤول لتقديم طلب رسمي أو شكوى إلى سلطة رقابية، فاسأل على العنوان أدناه وسيُبلَّغ إليك.",
      "offeredBy": "يطوّر Valnivo Labs تطبيق Valnivo ويقدّمه، ومقره لوكسمبورغ. Valnivo Labs اسم تجاري، وليس شركة مسجّلة."
    }
  }
} as const

export const IDENTITY_FINGERPRINT = '49f4334ee5af767ccc77a804d6c21117281c566afdffad37c23644238719fb4e'

export const ORGANISATION_NAME = IDENTITY_PAYLOAD.organisation.name

export type IdentityLang = keyof typeof IDENTITY_PAYLOAD.sentences

export const identityIn = (lang: string) =>
  IDENTITY_PAYLOAD.sentences[(lang in IDENTITY_PAYLOAD.sentences ? lang : 'en') as IdentityLang]
